### ISSUE TITLE
어셈블리를 공부하는데 굳이 책을 봐야할까요?

### ISSUE THREAD

**Issue by lsahn-gh** [gurugio/book_assembly_8086_ko#3]
공부라기 보다 Low-Level에 대한 이해도를 높이고 싶어서 보려고 하는데, 이 레파지토리 내용외에도 따로 책을 봐야할 정도일까요...?
아직 학생이고 관심분야는 유닉스 시스템, 커널, 디바이스 드라이버쪽이고 리눅스 응용 프로그래밍을 주로 하고 있습니다.
책을 보면서 하기에는 뭔가 불 필요하게 공부하는 듯한 느낌이 들어서요..

혹시 질문하기 위해서 이슈를 만드는 것이 불 필요하다면 앞으로는 메일로 드리겠습니다.

감사합니다. :)

**Comment by gurugio** [comment]
이 강좌를 보시면서 어셈블리가 대강 어떤식인지만 감을 잡고,
다른 관심분야를 공부하다가 어셈블리가 필요해질때 다시 필요한 내용만 확인하시는걸 추천합니다.

**Comment by lsahn-gh** [comment]
감사합니다 :)
