### ISSUE TITLE
블로그 주소가 안열려요 ㅠㅠ

### ISSUE THREAD

**Issue by serereuk** [gurugio/book_assembly_8086_ko#4]
안녕하세요! 우선 좋은 글 감사하다는 말씀을 먼저 드리고 싶습니다.

블로그를 참고해서 더 정보를 얻고 싶은데 열리지가 않네요 ㅠㅠ

**Comment by gurugio** [comment]
안녕하세요. 블로그에는 별다른 정보가 없어서 닫았습니다. 링크도 지워야되는데 깜빡했네요.
감사합니다.

**Comment by gurugio** [comment]
아 제 블로그가 아니라 kldp.net 사이트를 말씀하시는거였네요. 아쉽게도 kldp측 서버운영이 종료되서 자료가 없습니다. 너무 오래된 자료들이라 별도움은 안되실거에요.
